project_name: Asterisk Config
builds:
   - env:
        - CGO_ENABLED=0
     goos:
        - linux
        - darwin
        - windows
     goarch:
        - amd64

archive:
   format: tar.gz
   name_template: "{{ .Binary }}.{{ .Os }}.{{ .Arch }}"
   files:
      - 'defaults/*'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^doc:'
       - '^test:'

dockers:
   - image: cycoresystems/asterisk-config
     tag_templates:
        - "{{ .Tag }}"
        - "v{{ .Major }}"
        - "v{{ .Major }}.{{ .Minor }}"
        - latest
